name = "ProtoStructs"
uuid = "437b6fc4-8e8e-11e9-3fa1-ad391e66c018"
authors = ["Simon Christ"]
version = "1.1.6"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
